---
log:
  name: ""
  development: false
  level: info
  enable-color: false
  disable-caller: false
  disable-stacktrace: false
  format: console
  output-paths:
    - stdout
  error-output-paths:
    - stderr
  maxsize: 5
  maxage: 7
  maxbackups: 3
  compress: true
  port: 9090